name: Hprofile Actions

# Fixed: Structured the 'on' trigger to respond to pushes to the 'main' branch.
on:
  push:
    branches:
      - main

# Fixed: Separated 'jobs' into its own top-level section.
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Testing workflow
        uses: actions/checkout@v4
      - name: Maven test
        run: mvn test
      - name: Check style
        run: mvn checkstyle:checkstyle
