name: Hprofile Actions
on:
  push:
    branches:
      - main
jobs:
  build-and-scan:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for SonarQube to correctly track new code

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven' # Cache Maven dependencies to speed up future runs

      - name: Analyze with SonarScanner for Maven
        # This single command builds, tests, and runs the SonarQube analysis.
        run: mvn -B verify sonar:sonar \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.host.url=${{ secrets.SONAR_URL }} \
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
        env:
          # Pass the token securely as an environment variable
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # GITHUB_TOKEN is required for pull request decoration (optional)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
