name: Hprofile Actions

# Fixed: Structured the 'on' trigger to respond to pushes to the 'main' branch.
on:
  push:
    branches:
      - main
      - workflow_dispatch

# Fixed: Separated 'jobs' into its own top-level section.
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Testing workflow
        run: echo "Workflow works!"
