name: Hprofile Actions
on:
  push:
    branches:
      - main
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        # Fetch all history for accurate SCM info for SonarQube
        with:
          fetch-depth: 0

      # Set up Java 11 FIRST
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # Now run Maven commands
      - name: Maven test & Checkstyle
        run: |
          mvn test
          mvn checkstyle:checkstyle

      - name: Set up SonarQube scanner
        uses: warchant/setup-sonar-scanner@v7
      
      # CORRECTED SYNTAX for the run command
      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=src/ \
            -Dsonar.junit.reportsPath=target/surefire-reports/ \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
            -Dsonar.java.binaries=target/classes
